// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentHub.Data;

#nullable disable

namespace StudentHub.Migrations
{
    [DbContext(typeof(SimsDbContext))]
    [Migration("20260623083911_AddGoiYMonHocVuot")]
    partial class AddGoiYMonHocVuot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentHub.Models.BangDiem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DiemBaiTap")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("DiemBaiTap");

                    b.Property<string>("DiemChu")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("DiemChu");

                    b.Property<decimal?>("DiemChuyenCan")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("DiemChuyenCan");

                    b.Property<decimal?>("DiemCuoiKy")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("DiemCuoiKy");

                    b.Property<decimal?>("DiemGiuaKy")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("DiemGiuaKy");

                    b.Property<decimal?>("DiemTongKet")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("DiemTongKet");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LopHocId");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("SinhVienId");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("SinhVienId", "LopHocId")
                        .IsUnique();

                    b.ToTable("BangDiem");
                });

            modelBuilder.Entity("StudentHub.Models.CanhBaoSinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit")
                        .HasColumnName("DaDoc");

                    b.Property<string>("LoaiCanhBao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LoaiCanhBao");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LopHocId");

                    b.Property<string>("MucDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MucDo");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NoiDung");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("SinhVienId");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("SinhVienId", "LopHocId", "LoaiCanhBao")
                        .IsUnique()
                        .HasFilter("[DaDoc] = 0");

                    b.ToTable("CanhBaoSinhVien");
                });

            modelBuilder.Entity("StudentHub.Models.DangKyHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HocKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("HocKy");

                    b.Property<bool>("LaHocVuot")
                        .HasColumnType("bit")
                        .HasColumnName("LaHocVuot");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LopHocId");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NamHoc");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayDangKy");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("SinhVienId");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("SinhVienId", "LopHocId")
                        .IsUnique();

                    b.HasIndex("SinhVienId", "HocKy", "NamHoc", "LaHocVuot");

                    b.ToTable("DangKyHoc");
                });

            modelBuilder.Entity("StudentHub.Models.DiemDanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GhiChu");

                    b.Property<int>("PhienDiemDanhId")
                        .HasColumnType("int")
                        .HasColumnName("PhienDiemDanhId");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("SinhVienId");

                    b.Property<DateTime?>("ThoiGianCheckIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianCheckIn");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("SinhVienId");

                    b.HasIndex("PhienDiemDanhId", "SinhVienId")
                        .IsUnique();

                    b.ToTable("DiemDanh");
                });

            modelBuilder.Entity("StudentHub.Models.GiangVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("HoTen");

                    b.Property<string>("HocVi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HocVi");

                    b.Property<int>("KhoaId")
                        .HasColumnType("int")
                        .HasColumnName("KhoaId");

                    b.Property<string>("MaGiangVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaGiangVien");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SoDienThoai");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanId");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.HasIndex("MaGiangVien")
                        .IsUnique();

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("StudentHub.Models.GoiYHocVuot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiemPhuHop")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("DiemPhuHop");

                    b.Property<string>("HocKyGoiY")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("HocKyGoiY");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LopHocId");

                    b.Property<string>("LyDoGoiY")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("LyDoGoiY");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int")
                        .HasColumnName("MonHocId");

                    b.Property<string>("MucDoGoiY")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MucDoGoiY");

                    b.Property<string>("NamHocGoiY")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NamHocGoiY");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int")
                        .HasColumnName("SinhVienId");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("MonHocId");

                    b.HasIndex("HocKyGoiY", "NamHocGoiY", "MucDoGoiY", "TrangThai");

                    b.HasIndex("SinhVienId", "LopHocId", "HocKyGoiY", "NamHocGoiY")
                        .IsUnique();

                    b.ToTable("GoiYHocVuot");
                });

            modelBuilder.Entity("StudentHub.Models.Khoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaKhoa");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MoTa");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TenKhoa");

                    b.HasKey("Id");

                    b.HasIndex("MaKhoa")
                        .IsUnique();

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("StudentHub.Models.LichHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time")
                        .HasColumnName("GioBatDau");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time")
                        .HasColumnName("GioKetThuc");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LopHocId");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayBatDau");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayKetThuc");

                    b.Property<int>("PhongHocId")
                        .HasColumnType("int")
                        .HasColumnName("PhongHocId");

                    b.Property<int>("ThuTrongTuan")
                        .HasColumnType("int")
                        .HasColumnName("ThuTrongTuan");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("PhongHocId");

                    b.ToTable("LichHoc");
                });

            modelBuilder.Entity("StudentHub.Models.LopHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GiangVienId")
                        .HasColumnType("int")
                        .HasColumnName("GiangVienId");

                    b.Property<string>("HocKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("HocKy");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaLop");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int")
                        .HasColumnName("MonHocId");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NamHoc");

                    b.Property<int>("SoLuongToiDa")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongToiDa");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TenLop");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("MaLop")
                        .IsUnique();

                    b.HasIndex("MonHocId");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("StudentHub.Models.MonHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KhoaId")
                        .HasColumnType("int")
                        .HasColumnName("KhoaId");

                    b.Property<string>("MaMonHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaMonHoc");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MoTa");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int")
                        .HasColumnName("SoTinChi");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TenMonHoc");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.HasIndex("MaMonHoc")
                        .IsUnique();

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("StudentHub.Models.MonHocTienQuyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BatBuoc")
                        .HasColumnType("bit")
                        .HasColumnName("BatBuoc");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GhiChu");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int")
                        .HasColumnName("MonHocId");

                    b.Property<int>("MonHocTienQuyetId")
                        .HasColumnType("int")
                        .HasColumnName("MonHocTienQuyetId");

                    b.Property<string>("MucDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MucDo");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.HasKey("Id");

                    b.HasIndex("MonHocTienQuyetId");

                    b.HasIndex("MonHocId", "MonHocTienQuyetId")
                        .IsUnique();

                    b.ToTable("MonHocTienQuyet");
                });

            modelBuilder.Entity("StudentHub.Models.PhienDiemDanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DangMo")
                        .HasColumnType("bit")
                        .HasColumnName("DangMo");

                    b.Property<int>("GiangVienId")
                        .HasColumnType("int")
                        .HasColumnName("GiangVienId");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time")
                        .HasColumnName("GioBatDau");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time")
                        .HasColumnName("GioKetThuc");

                    b.Property<int>("LopHocId")
                        .HasColumnType("int")
                        .HasColumnName("LopHocId");

                    b.Property<string>("MaPhien")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("MaPhien");

                    b.Property<DateTime>("NgayDiemDanh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayDiemDanh");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("QrToken");

                    b.HasKey("Id");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("MaPhien")
                        .IsUnique();

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.ToTable("PhienDiemDanh");
                });

            modelBuilder.Entity("StudentHub.Models.PhongHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaPhong");

                    b.Property<int>("SucChua")
                        .HasColumnType("int")
                        .HasColumnName("SucChua");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TenPhong");

                    b.Property<string>("ViTri")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ViTri");

                    b.HasKey("Id");

                    b.HasIndex("MaPhong")
                        .IsUnique();

                    b.ToTable("PhongHoc");
                });

            modelBuilder.Entity("StudentHub.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DiaChi");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GioiTinh");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("HoTen");

                    b.Property<int>("KhoaId")
                        .HasColumnType("int")
                        .HasColumnName("KhoaId");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaSinhVien");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgaySinh");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SoDienThoai");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int")
                        .HasColumnName("TaiKhoanId");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.HasIndex("MaSinhVien")
                        .IsUnique();

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("StudentHub.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("HoTen");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MatKhauHash");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenDangNhap");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VaiTro");

                    b.HasKey("Id");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@sims.edu",
                            HoTen = "Quan tri he thong",
                            MatKhauHash = "AQAAAAIAAYagAAAAELJ93BmJta2AOWPv9xfXLLrTHv+they+ddyb08DDifof1TJY2qkgmhI7IopjW8HTlw==",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin",
                            TrangThai = "HoatDong",
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("StudentHub.Models.BangDiem", b =>
                {
                    b.HasOne("StudentHub.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("StudentHub.Models.CanhBaoSinhVien", b =>
                {
                    b.HasOne("StudentHub.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("StudentHub.Models.DangKyHoc", b =>
                {
                    b.HasOne("StudentHub.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("StudentHub.Models.DiemDanh", b =>
                {
                    b.HasOne("StudentHub.Models.PhienDiemDanh", "PhienDiemDanh")
                        .WithMany()
                        .HasForeignKey("PhienDiemDanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PhienDiemDanh");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("StudentHub.Models.GiangVien", b =>
                {
                    b.HasOne("StudentHub.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Khoa");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("StudentHub.Models.GoiYHocVuot", b =>
                {
                    b.HasOne("StudentHub.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("MonHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("StudentHub.Models.LichHoc", b =>
                {
                    b.HasOne("StudentHub.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.PhongHoc", "PhongHoc")
                        .WithMany()
                        .HasForeignKey("PhongHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("StudentHub.Models.LopHoc", b =>
                {
                    b.HasOne("StudentHub.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("StudentHub.Models.MonHoc", b =>
                {
                    b.HasOne("StudentHub.Models.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("StudentHub.Models.MonHocTienQuyet", b =>
                {
                    b.HasOne("StudentHub.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.MonHoc", "MonHocTienQuyetCuaMon")
                        .WithMany()
                        .HasForeignKey("MonHocTienQuyetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonHoc");

                    b.Navigation("MonHocTienQuyetCuaMon");
                });

            modelBuilder.Entity("StudentHub.Models.PhienDiemDanh", b =>
                {
                    b.HasOne("StudentHub.Models.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("StudentHub.Models.SinhVien", b =>
                {
                    b.HasOne("StudentHub.Models.Khoa", "Khoa")
                        .WithMany("SinhViens")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StudentHub.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Khoa");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("StudentHub.Models.Khoa", b =>
                {
                    b.Navigation("SinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
